export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const SHOP_ROUTE = '/catalog'
export const BASKET_ROUTE = '/basket'
export const DEVICE_ROUTE = '/product'
export const HOME_ROUTE  = '/'
export const ORDERS_ROUTE = '/orders'